### ISSUE TITLE
Cannot convert Keras MobileNet via CoreML

### ISSUE THREAD

**Issue by yieldthought** [dmlc/nnvm#195]
CoreML supports the Keras MobileNet, but converting this to NNML fails with "NotImplementedError: UnaryFunctionLayerParams is not supported"

```
import nnvm
from keras.applications import mobilenet
from coremltools.converters.keras import convert
keras_model = mobilenet.MobileNet(input_shape=(128, 128, 3), alpha=0.25, include_top=True)
coreml_model = convert(keras_model)
sym, params = nnvm.frontend.from_coreml(coreml_model)
```

MobileNet is likely to be a very common model to ship on devices and it'd be great if NNVM could handle this conversion path as it's the easiest way for developers to get a pretrained MobileNet sized to match their hardware.

**Comment by tqchen** [comment]
@zhreshold Can we add a quick support to this?

**Comment by zhreshold** [comment]
Let me have a look.

**Comment by zhreshold** [comment]
@yieldthought Do you have version info to share since I'm getting error inside coremltools converter using the snipes you provided

```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    coreml_model = convert(keras_model)
  File "/usr/local/lib/python2.7/dist-packages/coremltools/converters/keras/_keras_converter.py", line 504, in convert
    predicted_probabilities_output = predicted_probabilities_output)
  File "/usr/local/lib/python2.7/dist-packages/coremltools/converters/keras/_keras2_converter.py", line 278, in _convert
    converter_func(builder, layer, input_names, output_names, keras_layer)
  File "/usr/local/lib/python2.7/dist-packages/coremltools/converters/keras/_layers2.py", line 189, in convert_activation
    non_linearity = _get_activation_name_from_keras_layer(keras_layer)
  File "/usr/local/lib/python2.7/dist-packages/coremltools/converters/keras/_layers2.py", line 59, in _get_activation_name_from_keras_layer
    keras_layer.name)
  File "/usr/local/lib/python2.7/dist-packages/coremltools/converters/keras/_utils.py", line 12, in raise_error_unsupported_categorical_option
    layer_type, layer_name))
RuntimeError: Unsupported option activation=relu6 in layer Dense(conv1_relu)
```

**Comment by yieldthought** [comment]
@zhreshold Sure, I used the master branch of coremltools (https://github.com/apple/coremltools) - setup.py reports it as version 0.6.3.

**Comment by zhreshold** [comment]
@yieldthought 
Okay, I just figured out that this error is generated by coremltools itself, which means coremltools does not support this particular model. You need to sought support with apple guys.

**Comment by yieldthought** [comment]
@zhreshold Sorry for the delay, I've been travelling. Why do you think this is generated by coremltools? I see the exception raised by nnvm.frontend.from_coreml in nnvm/frontend/coreml.py, line 304.

Looks straight up as if the CoreML tools generate a layer type for MobileNet that is not yet supported to me. Am I misreading this?

```
>>> sym, params = nnvm.frontend.from_coreml(coreml_model)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/maroco01/anaconda3/envs/nnvm/lib/python2.7/site-packages/nnvm-0.8.0-py2.7.egg/nnvm/frontend/coreml.py", line 367, in from_coreml
    coreml_op_to_nnvm(layerop, l.input[0], l.output[0], symtab)
  File "/Users/maroco01/anaconda3/envs/nnvm/lib/python2.7/site-packages/nnvm-0.8.0-py2.7.egg/nnvm/frontend/coreml.py", line 304, in coreml_op_to_nnvm
    raise NotImplementedError("%s is not supported" % (classname))
NotImplementedError: UnaryFunctionLayerParams is not supported
```

**Comment by zhreshold** [comment]
@yieldthought 
It's a new message different from what I got in the past. I will figure it out.

**Comment by JingrenChen** [comment]
I tried to convert TensorFlow MobileNet via CoreML and got the same error as @yieldthought .
