### ISSUE TITLE
[OP] Support ceil_mode in pooling

### ISSUE THREAD

**Issue by gengtsh** [dmlc/nnvm#198]
i would appreciated if some one can help me out.
i try to run squeezenet model(downloaded from coreml website) on nnvm, and then i encounter the following issues: 
Traceback (most recent call last):
File "nnvm_coreml.py", line 63, in
graph, lib, params = nnvm.compiler.build(sym, target, shape_dict, params=params)
File "/nnvm/python/nnvm/compiler/build_module.py", line 237, in build
graph = graph.apply("GraphFusePartition").apply("GraphFuseCompile")
File "/nnvm/python/nnvm/graph.py", line 234, in apply
check_call(_LIB.NNGraphApplyPasses(self.handle, npass, cpass, ctypes.byref(ghandle)))
File "/nnvm/python/nnvm/_base.py", line 72, in check_call
raise NNVMError(py_str(_LIB.NNGetLastError()))
nnvm._base.NNVMError: TVMCall CFunc Error:
Traceback (most recent call last):
File "/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun
rv = local_pyfunc(*pyargs)
File "/nnvm/python/nnvm/top/nn.py", line 139, in compute_max_pool2d
assert not ceil_mode, "not support ceil_mode now"
AssertionError: not support ceil_mode now

**Comment by tqchen** [comment]
This is because ceil_mode is not currently supported in topi. @zhreshold @Huyuwei is it possible to support ceil mode using floor mode, by inferring the pad_after value correctly?

**Comment by tqchen** [comment]
please check if the current version in the master fixed the issue

**Comment by gengtsh** [comment]
yes, this problem is solved. thank you so much. but it encountered other problem. i will create a new issue to talk about it.
