### ISSUE TITLE
[get_started.py][windows]RuntimeError: Compilation error: b'dllmain.cc(1): fatal error C1034: windows.h: no include path set\r\nGenerating Code...\r\n'

### ISSUE THREAD

**Issue by BigJerry** [dmlc/nnvm#227]
completed output and traceback:
-------compute graph-------
Graph(%x, %y) {
  %2 = sqrt(%y)
  %3 = elemwise_add(%x, %2)
  ret %3
}
-------deploy graph-------
Graph(%x, %y) {
  %2 = tvm_op(%x, %y, flatten_data='1', func_name='fuse_sqrt_elemwise_add', num_inputs='2', num_outputs='1')
  ret %2
}
graph_attr_keys = [storage_id, shape, dtype, dltype, storage_allocated_bytes, storage_inplace_index, storage_num_not_allocated]

-------deploy library-------
extern "C" __global__ void fuse_sqrt_elemwise_add__kernel0(float* __restrict__ input1_compute_add, float* __restrict__ input1, float* __restrict__ input0) {
  if (((int)threadIdx.x) < 4) {
    input1_compute_add[((int)threadIdx.x)] = (input1[((int)threadIdx.x)] + sqrtf(input0[((int)threadIdx.x)]));
  }
}

[ 3.  4.  5.  6.]
-----optimized params-----
{'sqrt0': <tvm.NDArray shape=(4,), cpu(0)>
array([ 2.,  2.,  2.,  2.], dtype=float32)}
-------deploy library-------
extern "C" __global__ void fuse_elemwise_add__kernel0(float* __restrict__ input0_input1_add, float* __restrict__ input0, float* __restrict__ input1) {
  if (((int)threadIdx.x) < 4) {
    input0_input1_add[((int)threadIdx.x)] = (input0[((int)threadIdx.x)] + input1[((int)threadIdx.x)]);
  }
}

Traceback (most recent call last):

  File "<ipython-input-1-839d35813a22>", line 1, in <module>
    runfile('E:/MyCodes/PythonCodes/Learning/NNVM_Learning/NNVM_Learning.py', wdir='E:/MyCodes/PythonCodes/Learning/NNVM_Learning')

  File "E:\PythonAnaconda\Anaconda\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "E:\PythonAnaconda\Anaconda\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "E:/MyCodes/PythonCodes/Learning/NNVM_Learning/NNVM_Learning.py", line 125, in <module>
    lib.export_library(path_lib)

  File "C:\Users\zhangzhiwei\AppData\Roaming\Python\Python35\site-packages\tvm-0.1.0-py3.5-win-amd64.egg\tvm\module.py", line 111, in export_library
    fcompile(file_name, files, **kwargs)

  File "C:\Users\zhangzhiwei\AppData\Roaming\Python\Python35\site-packages\tvm-0.1.0-py3.5-win-amd64.egg\tvm\contrib\cc.py", line 34, in create_shared
    _windows_shared(output, objects, options)

  File "C:\Users\zhangzhiwei\AppData\Roaming\Python\Python35\site-packages\tvm-0.1.0-py3.5-win-amd64.egg\tvm\contrib\cc.py", line 92, in _windows_shared
    raise RuntimeError(msg)

RuntimeError: Compilation error:
b'....（ignoring）....  dllmain.cc(1): fatal error C1034: windows.h: no include path set\r\nGenerating Code...\r\n'

**Comment by tqchen** [comment]
@yajiedesign any suggestions?

**Comment by yajiedesign** [comment]
please run py script in `x64 Native Tools Command Prompt for VS xxxx` or `x86 Native Tools Command Prompt for VS`

**Comment by BigJerry** [comment]
It works, thx for guide to  novice.  @yajiedesign
