### ISSUE TITLE
RuntimeError: Batch size: 64 is too large for this schedule

### ISSUE THREAD

**Issue by BigJerry** [dmlc/nnvm#235]
layout = "NCHW"
data_shape = (1,1,256,256)
graph_net, lib, params = nnvm.compiler.build(net, target='cuda', shape={"data":data_shape}, 
dtype="float32",params=params)

error occurred at nnvm.compiler.build. only if "target" was set to 'llvm' , the compilation pass, otherwise(in the cases target='cuda' or target='opencl' or target='rocm') it will throw this Error.I'm wondering why it say that the batch size is 64 even if data_shape = (1,1,256,256) ???

NNVMError: TVMCall CFunc Error:
Traceback (most recent call last):
  File "C:\Users\zhangzhiwei\AppData\Roaming\Python\Python35\site-packages\tvm-0.1.0-py3.5-win-amd64.egg\tvm\_ffi\_ctypes\function.py", line 54, in cfun
    rv = local_pyfunc(*pyargs)
  File "C:\Users\zhangzhiwei\AppData\Roaming\Python\Python35\site-packages\nnvm-0.8.0-py3.5.egg\nnvm\top\nn.py", line 123, in schedule_conv2d
    return topi.generic.schedule_conv2d_nchw(outs)
  File "<decorator-gen-159>", line 2, in schedule_conv2d_nchw
  File "C:\Users\zhangzhiwei\AppData\Roaming\Python\Python35\site-packages\tvm-0.1.0-py3.5-win-amd64.egg\tvm\target.py", line 218, in dispatch_func
    return dispatch_dict[k](*args, **kwargs)
  File "C:\Users\zhangzhiwei\AppData\Roaming\Python\Python35\site-packages\topi-0.1.0-py3.5.egg\topi\cuda\conv2d_nchw.py", line 509, in schedule_conv2d_nchw
    raise RuntimeError("Batch size: %d is too large for this schedule" % batch_size)
RuntimeError: Batch size: 64 is too large for this schedule

**Comment by BigJerry** [comment]
changing "axis" (which was 0) to 1 fixes this problem.
