### ISSUE TITLE
check extents failed when building conv

### ISSUE THREAD

**Issue by xqdan** [dmlc/nnvm#239]
Traceback (most recent call last):
  File "pavnet.py", line 36, in <module>
    graph, lib, params = nnvm.compiler.build(nnvm_sym[0], target, shape_dict, params=nnvm_params)
  File "/home/danxiaoqiang/nnvm/python/nnvm/compiler/build_module.py", line 237, in build
    graph = graph.apply("GraphFusePartition").apply("GraphFuseCompile")
  File "/home/danxiaoqiang/nnvm/python/nnvm/graph.py", line 234, in apply
    check_call(_LIB.NNGraphApplyPasses(self.handle, npass, cpass, ctypes.byref(ghandle)))
  File "/home/danxiaoqiang/nnvm/python/nnvm/_base.py", line 72, in check_call
    raise NNVMError(py_str(_LIB.NNGetLastError()))
nnvm._base.NNVMError: TVMCall CFunc Error:
Traceback (most recent call last):
  File "/home/danxiaoqiang/nnvm/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun
    rv = local_pyfunc(*pyargs)
  File "/home/danxiaoqiang/nnvm/python/nnvm/compiler/build_module.py", line 109, in _lower
    raise RuntimeError(msg)
RuntimeError: Traceback (most recent call last):
  File "/home/danxiaoqiang/nnvm/python/nnvm/compiler/build_module.py", line 102, in _lower
    f = tvm.lower(sch, inputs, name=func_name)
  File "/home/danxiaoqiang/nnvm/tvm/python/tvm/build_module.py", line 210, in lower
    bounds = schedule.InferBound(sch)
  File "/home/danxiaoqiang/nnvm/tvm/python/tvm/_ffi/function.py", line 255, in my_api_func
    return flocal(*args)
  File "/home/danxiaoqiang/nnvm/tvm/python/tvm/_ffi/_ctypes/function.py", line 183, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "/home/danxiaoqiang/nnvm/tvm/python/tvm/_ffi/base.py", line 62, in check_call
    raise TVMError(py_str(_LIB.TVMGetLastError()))
TVMError: [17:47:41] src/schedule/message_passing.cc:36: Check failed: match iter_var(threadIdx.x, Range(min=0, extent=7), threadIdx.x) domain already inferred, cannot prove their extents are the same 6 vs 7

Error during compile graph
--------------------------
Graph(%input0, %input1, %input2) {
  %input0, shape=[1,96,14,14]
  %input1, shape=[96,96,1,1]
  %input2, shape=[96]
  %3 = conv2d(%input0, %input1, %input2, kernel_size='[1, 1]', use_bias='True', dilation='(1, 1)', groups='1', padding='(0, 0)', strides='(1, 1)', layout='NCHW', channels='96'), shape=[1,96,14,14]
  %4 = relu(%3), shape=[1,96,14,14]
  ret %4
}
graph_attr_keys = [dtype_num_unknown_nodes, dtype, shape_num_unknown_nodes, shape]

**Comment by tqchen** [comment]
cc @Laurawly maybe this is due to specific shape not supported in conv schedule, as referenced in the graph

**Comment by tqchen** [comment]
should be fixed by @239
