### ISSUE TITLE
[Front end] not support float tuple

### ISSUE THREAD

**Issue by xqdan** [dmlc/nnvm#255]
nnvm front end donesn't support float tuple right now.

when supporting new Op in front end, there is no method to parse  float tuple;
```
Op:Proposal, Name=proposal0
Inputs:
	arg[0]=reshape1(0)
	arg[1]=conv2d37(0)
	arg[2]=im_info(0) version=0
Attrs:
	feature_stride=16
	iou_loss=True
	output_index4bbox=False
	output_score=False
	ratios=[0.333, 0.5, 0.667, 1.0, 1.5, 2.0, 3.0]
	rpn_min_size=16
	rpn_post_nms_top_n=200
	rpn_pre_nms_top_n=3000
	scales=[2.0, 3.0, 6.0, 9.0, 16.0, 32.0]
	threshold=0.7
```
when we add one parse function for that. got error:
if without patch below, no this error comes out.

```
--- a/src/top/nn/nn.cc
+++ b/src/top/nn/nn.cc
@@ -133,6 +133,7 @@ NNVM_REGISTER_OP(Proposal)
 .add_argument("bbox_pred", "NDArray-or-Symbol", "BBox Predicted deltas from anchors for proposals")
 .add_argument("im_info", "NDArray-or-Symbol", "Image size and scale.")
 .add_arguments(ProposalParam::__FIELDS__())
+.set_attr_parser(ParamParser<ProposalParam>)
 .set_num_outputs(3)
 .set_num_inputs(3);

@@ -148,6 +149,7 @@ NNVM_REGISTER_OP(PSROIPooling)
 "of designated region of interest. batch_index indicates the index of corresponding image "
 "in the input data")
 .add_arguments(PSROIPoolingParam::__FIELDS__())
+.set_attr_parser(ParamParser<PSROIPoolingParam>)
 .set_num_outputs(1)
 .set_num_inputs(2);
```

```
Traceback (most recent call last):
  File "pvanet.py", line 27, in <module>
    nnvm_sym, nnvm_params = nnvm.frontend.from_mxnet(mx_sym, args, auxs)
  File "/home/danxiaoqiang/nnvm/python/nnvm/frontend/mxnet.py", line 380, in from_mxnet
    sym = _from_mxnet_impl(symbol, {})
  File "/home/danxiaoqiang/nnvm/python/nnvm/frontend/mxnet.py", line 332, in _from_mxnet_impl
    return [_from_mxnet_impl(s, graph) for s in symbol]
  File "/home/danxiaoqiang/nnvm/python/nnvm/frontend/mxnet.py", line 343, in _from_mxnet_impl
    childs = [_from_mxnet_impl(c, graph) for c in _as_list(childs)]
  File "/home/danxiaoqiang/nnvm/python/nnvm/frontend/mxnet.py", line 343, in _from_mxnet_impl
    childs = [_from_mxnet_impl(c, graph) for c in _as_list(childs)]
  File "/home/danxiaoqiang/nnvm/python/nnvm/frontend/mxnet.py", line 332, in _from_mxnet_impl
    return [_from_mxnet_impl(s, graph) for s in symbol]
  File "/home/danxiaoqiang/nnvm/python/nnvm/frontend/mxnet.py", line 345, in _from_mxnet_impl
    node = _convert_symbol(op_name, childs, attr)
  File "/home/danxiaoqiang/nnvm/python/nnvm/frontend/mxnet.py", line 299, in _convert_symbol
    sym = convert_map[op_name](inputs, attrs)
  File "/home/danxiaoqiang/nnvm/python/nnvm/frontend/mxnet.py", line 211, in _Proposal
    return _get_nnvm_op(op_name)(*inputs, **new_attrs)
  File "/home/danxiaoqiang/nnvm/python/nnvm/_ctypes/symbol.py", line 181, in creator
    ctypes.byref(sym_handle)))
  File "/home/danxiaoqiang/nnvm/python/nnvm/_base.py", line 72, in check_call
    raise NNVMError(py_str(_LIB.NNGetLastError()))
nnvm._base.NNVMError: Invalid Parameter format for scales expect  but value='[2.0, 3.0, 6.0, 9.0, 16.0, 32.0]', in operator Proposal(name="", threshold="0.7", feature_stride="16", output_index4bbox="False", rpn_post_nms_top_n="200", scales="[2.0, 3.0, 6.0, 9.0, 16.0, 32.0]", rpn_min_size="16", ratios="[0.333, 0.5, 0.667, 1.0, 1.5, 2.0, 3.0]", iou_loss="True", rpn_pre_nms_top_n="3000", output_score="False"
```)

**Comment by hiranoaya** [comment]
we add **_parse_float_tuple** in mxnet.py like _parse_tshape

```
def _parse_float_tuple(tshape):

    """Parse tshape in string."""
    return [float(x.strip()) for x in tshape.strip('()').split(',')]
```

and **get_float_tuple** in class.AttrDict to support  float tuple
```
def get_float_tuple(self, key):
    return tuple(float(x) for x in self[key][1:-1].split(",") if x)
```

go through without **ParamParser\<PType\>**

**NumericalParam\<float\>**   parse fail ?


BTW, 
TVMArgValue  to pass args for packfunc support 
base: int double bool 
extern: graph symbol AttrDict

now we flatten the tuple to pass elem one by one

**Comment by xqdan** [comment]
Root cause found:
after parsing in mx:
```
Op:Proposal, Name=proposal
	scales=(2.0, 3.0, 6.0, 9.0, 16.0, 32.0)
```
however, in the parse float tuple we add by ourslef, output is,
`scales=[2.0, 3.0, 6.0, 9.0, 16.0, 32.0]`

so failed when do n->op()->attr_parser(&(n->attrs)); because of wrong format

**Comment by tqchen** [comment]
this seems to be an reasonable solution, try to pr the function ?
