### ISSUE TITLE
check extents failed when building conv of MXNET Inception v3

### ISSUE THREAD

**Issue by TianXIA88** [dmlc/nnvm#293]
```
Traceback (most recent call last):
  File "from_mxnet_cpu.py", line 105, in <module>
    graph, lib, params = nnvm.compiler.build(sym, target, shape_dict, params=params)
  File "/mnt/sdb/xt/machine_learning/nnvm/nnvm/python/nnvm/compiler/build_module.py", line 250, in build
    graph = graph.apply("GraphFusePartition").apply("GraphFuseCompile")
  File "/mnt/sdb/xt/machine_learning/nnvm/nnvm/python/nnvm/graph.py", line 235, in apply
    check_call(_LIB.NNGraphApplyPasses(self.handle, npass, cpass, ctypes.byref(ghandle)))
  File "/mnt/sdb/xt/machine_learning/nnvm/nnvm/python/nnvm/_base.py", line 72, in check_call
    raise NNVMError(py_str(_LIB.NNGetLastError()))
nnvm._base.NNVMError: TVMCall CFunc Error:
Traceback (most recent call last):
  File "/mnt/sdb/xt/machine_learning/nnvm/tvm/python/tvm/_ffi/_ctypes/function.py", line 54, in cfun
    rv = local_pyfunc(*pyargs)
  File "/mnt/sdb/xt/machine_learning/nnvm/nnvm/python/nnvm/compiler/build_module.py", line 109, in _lower
    raise RuntimeError(msg)
RuntimeError: Traceback (most recent call last):
  File "/mnt/sdb/xt/machine_learning/nnvm/nnvm/python/nnvm/compiler/build_module.py", line 102, in _lower
    f = tvm.lower(sch, inputs, name=func_name)
  File "/mnt/sdb/xt/machine_learning/nnvm/tvm/python/tvm/build_module.py", line 214, in lower
    bounds = schedule.InferBound(sch)
  File "/mnt/sdb/xt/machine_learning/nnvm/tvm/python/tvm/_ffi/function.py", line 255, in my_api_func
    return flocal(*args)
  File "/mnt/sdb/xt/machine_learning/nnvm/tvm/python/tvm/_ffi/_ctypes/function.py", line 183, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "/mnt/sdb/xt/machine_learning/nnvm/tvm/python/tvm/_ffi/base.py", line 62, in check_call
    raise TVMError(py_str(_LIB.TVMGetLastError()))
TVMError: [09:54:09] src/schedule/message_passing.cc:36: Check failed: match iter_var(threadIdx.x, Range(min=0, extent=8), threadIdx.x) domain already inferred, cannot prove their extents are the same 7 vs 8

Stack trace returned 10 entries:
[bt] (0) /mnt/sdb/xt/machine_learning/nnvm/tvm/lib/libtvm.so(_ZN4dmlc10StackTraceEv+0x3d) [0x7f2c7e24388d]
[bt] (1) /mnt/sdb/xt/machine_learning/nnvm/tvm/lib/libtvm.so(_ZN4dmlc15LogMessageFatalD1Ev+0x18) [0x7f2c7e243b48]
[bt] (2) /mnt/sdb/xt/machine_learning/nnvm/tvm/lib/libtvm.so(_ZN3tvm8schedule6UpdateEPSt13unordered_mapINS_7IterVarENS_5RangeESt4hashIS2_ESt8equal_toIS2_ESaISt4pairIKS2_S3_EEERS9_S3_+0x3e5) [0x7f2c7e348525]
[bt] (3) /mnt/sdb/xt/machine_learning/nnvm/tvm/lib/libtvm.so(_ZN3tvm8schedule14PassDownDomainERKNS_5StageEPSt13unordered_mapINS_7IterVarENS_5RangeESt4hashIS5_ESt8equal_toIS5_ESaISt4pairIKS5_S6_EEEb+0x9a8) [0x7f2c7e349118]
[bt] (4) /mnt/sdb/xt/machine_learning/nnvm/tvm/lib/libtvm.so(_ZN3tvm8schedule10InferBoundERKNS_8ScheduleE+0xb8f) [0x7f2c7e37c62f]
[bt] (5) /mnt/sdb/xt/machine_learning/nnvm/tvm/lib/libtvm.so(+0x9ad6ff) [0x7f2c7e3896ff]
[bt] (6) /mnt/sdb/xt/machine_learning/nnvm/tvm/lib/libtvm.so(TVMFuncCall+0x52) [0x7f2c7e5e0d02]
[bt] (7) /lib64/libffi.so.6(ffi_call_unix64+0x4c) [0x7f2cb9532dcc]
[bt] (8) /lib64/libffi.so.6(ffi_call+0x1f5) [0x7f2cb95326f5]
[bt] (9) /usr/lib64/python2.7/lib-dynload/_ctypes.so(_ctypes_callproc+0x30b) [0x7f2cb9745c8b]


Error during compile graph
--------------------------
Graph(%input0,
      %input1,
      %input2,
      %input3) {
  %input0, shape=[1,96,35,35]
  %input1, shape=[96,96,3,3]
  %input2, shape=[96,1,1]
  %input3, shape=[96,1,1]
  %2 = conv2d(%input0, %input1, kernel_size='[3, 3]', use_bias='False', dilation='(1, 1)', groups='1', padding='(0, 0)', strides='(2, 2)', layout='NCHW', channels='96'), shape=[1,96,17,17]
  %4 = broadcast_mul(%2, %input2), shape=[1,96,17,17]
  %6 = broadcast_add(%4, %input3), shape=[1,96,17,17]
  %7 = relu(%6), shape=[1,96,17,17]
  ret %7
}
graph_attr_keys = [dtype_num_unknown_nodes, dtype, shape_num_unknown_nodes, shape]

```
This error occurs when compiling InceptionV3 Net with input shape (299, 299).
I believe this issue is alike [#issue 239](https://github.com/dmlc/nnvm/issues/239), where  **specific shape is not supported in conv schedule**, since the model requires a conv shape [1,96,17,17]

Could anyone help fix this please?

**Comment by tqchen** [comment]
cc @Laurawly

**Comment by Laurawly** [comment]
@tqchen I tried verify_conv2d_nchw(1, 96, 17, 96, 3, 2, 0) in tvm/topi/tests/python/test_topi_conv2d_nchw.py on K80c GPU and it runs fine. I wonder I'm doing the test correctly.

**Comment by TianXIA88** [comment]
@Laurawly Actually my situation is that I tried to run MXNET InceptionV3 model (pulled from gluon repo) with input image size (299,299). 
Besides, I am using GPU P4 and Cuda 8.0 , but I doubt whether the environment matters in this issue...

**Comment by tqchen** [comment]
close due to inactive status, future discussions are welcomed at https://discuss.tvmlang.org/
