### ISSUE TITLE
Keras layer UpSampling2D not supported

### ISSUE THREAD

**Issue by thefiddler** [dmlc/nnvm#304]
I have successfully built and install tvm, topi and nnvm with the openblas and opencl backends.

While trying to convert a [simple keras model](https://github.com/dmlc/nnvm/files/1628389/simple.yml.txt), I am encountering the following error:
```bash
Traceback (most recent call last):
  File "compile_nnvm.py", line 6, in <module>
    sym, params = nnvm.frontend.from_keras(model)
  File "/Users/thefiddler/.virtualenvs/nnvm/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/frontend/keras.py", line 445, in from_keras
    _check_unsupported_layers(model)
  File "/Users/thefiddler/.virtualenvs/nnvm/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/frontend/keras.py", line 396, in _check_unsupported_layers
    raise ValueError("Keras layer {} not supported.".format(type(layer).__name__))
ValueError: Keras layer UpSampling2D not supported.
```

What would be the simplest way to add support for the UpSampling2D layer?

Edit: I am noticing that UpSampling2D is explicitly commented out in [keras.py:370](https://github.com/dmlc/nnvm/blob/master/python/nnvm/frontend/keras.py#L370).

Edit 2: I am preparing a PR to add support for keras upsampling.

**Comment by thefiddler** [comment]
PR has been merged, closing!
