### ISSUE TITLE
Crash in keras frontend when converting unet-style network

### ISSUE THREAD

**Issue by thefiddler** [dmlc/nnvm#312]
When trying to use the keras frontend to convert a [unet-style model](https://github.com/retinai/nnvm/blob/f3cb3d2472cdedbd31ca4cb049d4fafdec91a8b3/tests/python/frontend/keras/test_forward.py#L221-L235), I am getting the following crash:

```bash
$ python3 test_forward.py
$ python3 test_forward.py
TVM: Initializing cython mode...
Using TensorFlow backend.
test_forward_unet
Traceback (most recent call last):
  File "test_forward.py", line 253, in <module>
    test_forward_unet()
  File "test_forward.py", line 235, in test_forward_unet
    verify_keras_frontend(keras_model)
  File "test_forward.py", line 41, in verify_keras_frontend
    tvm_out = get_tvm_output(x.transpose([0,3,1,2]), target, ctx)
  File "test_forward.py", line 30, in get_tvm_output
    graph, lib, params = nnvm.compiler.build(sym, target, shape_dict, params=params)
  File "/Users/build/.virtualenvs/nnvm/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/compiler/build_module.py", line 251, in build
    graph = graph.apply("GraphFusePartition").apply("GraphFuseCompile")
  File "/Users/build/.virtualenvs/nnvm/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/graph.py", line 235, in apply
    check_call(_LIB.NNGraphApplyPasses(self.handle, npass, cpass, ctypes.byref(ghandle)))
  File "/Users/build/.virtualenvs/nnvm/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/_base.py", line 72, in check_call
    raise NNVMError(py_str(_LIB.NNGetLastError()))
nnvm._base.NNVMError: TVMCall CFunc Error:
Traceback (most recent call last):
  File "tvm/_ffi/_cython/function.pxi", line 39, in core.tvm_callback (tvm/_ffi/_cython/core.cpp:3206)
  File "/Users/build/.virtualenvs/nnvm/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/compiler/build_module.py", line 119, in _build
    return tvm.build(funcs, target=target, target_host=target_host)
  File "/Users/build/.virtualenvs/nnvm/lib/python3.6/site-packages/tvm-0.1.0-py3.6-macosx-10.12-x86_64.egg/tvm/build_module.py", line 361, in build
    mhost = codegen.build_module(fhost, str(target_host))
  File "/Users/build/.virtualenvs/nnvm/lib/python3.6/site-packages/tvm-0.1.0-py3.6-macosx-10.12-x86_64.egg/tvm/codegen.py", line 20, in build_module
    return _Build(lowered_func, target)
  File "/Users/build/.virtualenvs/nnvm/lib/python3.6/site-packages/tvm-0.1.0-py3.6-macosx-10.12-x86_64.egg/tvm/_ffi/function.py", line 255, in my_api_func
    return flocal(*args)
  File "tvm/_ffi/_cython/function.pxi", line 264, in core.FunctionBase.__call__ (tvm/_ffi/_cython/core.cpp:6958)
  File "tvm/_ffi/_cython/function.pxi", line 213, in core.FuncCall (tvm/_ffi/_cython/core.cpp:6180)
  File "tvm/_ffi/_cython/function.pxi", line 205, in core.FuncCall3 (tvm/_ffi/_cython/core.cpp:6083)
  File "tvm/_ffi/_cython/base.pxi", line 131, in core.CALL (tvm/_ffi/_cython/core.cpp:1849)
tvm._ffi.base.TVMError: b'[15:07:41] src/codegen/llvm/codegen_cpu.cc:417: Check failed: par_env.parallel_loop_count != 0 (0 vs. 0) Cannot find parallel loop within parallel launch\n\nStack trace returned 10 entries:\n[bt] (0) 0   libtvm.dylib                        0x00000001044b4d0f dmlc::StackTrace() + 303\n[bt] (1) 1   libtvm.dylib                        0x00000001044b4aaf dmlc::LogMessageFatal::~LogMessageFatal() + 47\n[bt] (2) 2   libtvm.dylib                        0x00000001046fb854 tvm::codegen::CodeGenCPU::CreateParallelLaunch(HalideIR::Internal::Stmt const&, int) + 2580\n[bt] (3) 3   libtvm.dylib                        0x000000010454005e tvm::IRFunctor<void (tvm::NodeRef const&, tvm::ir::StmtFunctor<void (HalideIR::Internal::Stmt const&)>*)>::operator()(tvm::NodeRef const&, tvm::ir::StmtFunctor<void (HalideIR::Internal::Stmt const&)>*) const + 126\n[bt] (4) 4   libtvm.dylib                        0x000000010454005e tvm::IRFunctor<void (tvm::NodeRef const&, tvm::ir::StmtFunctor<void (HalideIR::Internal::Stmt const&)>*)>::operator()(tvm::NodeRef const&, tvm::ir::StmtFunctor<void (HalideIR::Internal::Stmt const&)>*) const + 126\n[bt] (5) 5   libtvm.dylib                        0x000000010470ed77 non-virtual thunk to tvm::codegen::CodeGenLLVM::VisitStmt_(HalideIR::Internal::Block const*) + 23\n[bt] (6) 6   libtvm.dylib
                    0x000000010454005e tvm::IRFunctor<void (tvm::NodeRef const&, tvm::ir::StmtFunctor<void (HalideIR::Internal::Stmt const&)>*)>::operator()(tvm::NodeRef const&, tvm::ir::StmtFunctor<void (HalideIR::Internal::Stmt const&)>*) const + 126\n[bt] (7) 7   libtvm.dylib                        0x000000010454005e tvm::IRFunctor<void (tvm::NodeRef const&, tvm::ir::StmtFunctor<void (HalideIR::Internal::Stmt const&)>*)>::operator()(tvm::NodeRef const&, tvm::ir::StmtFunctor<void (HalideIR::Internal::Stmt const&)>*) const + 126\n[bt] (8) 8   libtvm.dylib                        0x000000010454005e tvm::IRFunctor<void (tvm::NodeRef const&, tvm::ir::StmtFunctor<void (HalideIR::Internal::Stmt const&)>*)>::operator()(tvm::NodeRef const&, tvm::ir::StmtFunctor<void (HalideIR::Internal::Stmt const&)>*) const + 126\n[bt] (9) 9   libtvm.dylib                        0x000000010454005e tvm::IRFunctor<void (tvm::NodeRef const&, tvm::ir::StmtFunctor<void (HalideIR::Internal::Stmt const&)>*)>::operator()(tvm::NodeRef const&, tvm::ir::StmtFunctor<void (HalideIR::Internal::Stmt const&)>*) const + 126\n\n'
```

This is using a freshly-built master branch of TVM and NNVM, on Mac OS, using the LLVM backend. A similar-looking crash can also be seen in the log of #311

**Comment by Huyuwei** [comment]
This error is due to the conv schedule on cpu. It can be temporarily fixed after commenting out two lines in https://github.com/dmlc/tvm/blob/9800fe205340435b8fd72c12f686df1139809c72/topi/python/topi/x86/conv2d.py

```python
s[C].parallel(c)
s[C].pragma(n, "parallel_launch_point")
```

**Comment by thefiddler** [comment]
Thanks, I tried commenting out those two lines and rebuilding TVM & NNVM, but I'm still getting the exact same stack trace. Could it be that I'm building it wrong? I'm using the following script:
```bash
# cleanup
cd ~/nnvm && make clean
cd tvm && make clean

# build tvm
make -j && cd python && python3 setup.py install

# build nnvm
cd ../../
make -j && cd python && python3 setup.py install

# test
cd ../tests/python/frontend/keras
python3 test_forward.py
```

**Comment by Huyuwei** [comment]
topi won't be installed together with tvm, it's a separate package.

Besides, it's recommended to set the environment variable PYTHONPATH, see https://github.com/dmlc/tvm/blob/master/docs/how_to/install.md the last part.

**Comment by thefiddler** [comment]
Ah, thanks, I've updated my build script to install topi and the workaround is working now.

Should I close this bug in favor of https://github.com/dmlc/tvm/issues/787?

**Comment by tqchen** [comment]
move to dmlc/tvm#787
