### ISSUE TITLE
Keras frontend: adding down/upsampled layers causes crash in optimizer

### ISSUE THREAD

**Issue by thefiddler** [dmlc/nnvm#327]
The following code crashes when compiling with `opt_level=1` or `opt_level=2`. It works when `opt_level=0`.

```python
from keras.layers import *
from keras.models import Model

x = input = Input((32, 32, 1))
r = Conv2D(2, (3, 3), padding="valid")(x)
x = Conv2D(2, (3, 3), strides=(2, 2), padding="valid")(x)
x = UpSampling2D()(x)
x = add([x, r])
x = Conv2D(1, (1, 1))(x)
model = keras.models.Model(input, x)

verify_keras_frontend(model)
```

Log:
```bash
[12:36:58] src/pass/vectorize_loop.cc:303: Detect vector condition in Vectorized Loop, scalarizing...
[12:36:58] src/pass/vectorize_loop.cc:303: Detect vector condition in Vectorized Loop, scalarizing...
[12:36:58] src/pass/vectorize_loop.cc:303: Detect vector condition in Vectorized Loop, scalarizing...
[12:36:58] src/pass/vectorize_loop.cc:303: Detect vector condition in Vectorized Loop, scalarizing...
[12:36:58] src/pass/vectorize_loop.cc:303: Detect vector condition in Vectorized Loop, scalarizing...
[12:36:58] src/pass/vectorize_loop.cc:303: Detect vector condition in Vectorized Loop, scalarizing...
[12:36:58] src/pass/vectorize_loop.cc:303: Detect vector condition in Vectorized Loop, scalarizing...
[12:36:58] src/pass/vectorize_loop.cc:303: Detect vector condition in Vectorized Loop, scalarizing...
Traceback (most recent call last):
  File "nnvm_compile.py", line 135, in <module>
    verify_keras_frontend(model)
  File "nnvm_compile.py", line 56, in verify_keras_frontend
    y_tvm = get_tvm_output(x.transpose([0,3,1,2]), target, ctx)
  File "nnvm_compile.py", line 34, in get_tvm_output
    graph, lib, params = nnvm.compiler.build(sym, target, shape_dict, params=params)
  File "/Users/test/.virtualenvs/nnvm/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/compiler/build_module.py", line 251, in build
    graph = graph.apply("GraphFusePartition").apply("GraphFuseCompile")
  File "/Users/test/.virtualenvs/nnvm/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/graph.py", line 234, in apply
    check_call(_LIB.NNGraphApplyPasses(self.handle, npass, cpass, ctypes.byref(ghandle)))
  File "/Users/test/.virtualenvs/nnvm/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/_base.py", line 72, in check_call
    raise NNVMError(py_str(_LIB.NNGetLastError()))
nnvm._base.NNVMError: TVMCall CFunc Error:
Traceback (most recent call last):
  File "/Users/test/.virtualenvs/nnvm/lib/python3.6/site-packages/tvm-0.1.0-py3.6-macosx-10.13-x86_64.egg/tvm/_ffi/_ctypes/function.py", line 54, in cfun
    rv = local_pyfunc(*pyargs)
  File "/Users/test/.virtualenvs/nnvm/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/top/tensor.py", line 37, in _compute
    return f(x[0], x[1])
  File "/Users/test/.virtualenvs/nnvm/lib/python3.6/site-packages/topi-0.1.0-py3.6.egg/topi/broadcast.py", line 169, in broadcast_add
    return broadcast_binary_op(lhs, rhs, lambda a, b: a + b, "add")
  File "<decorator-gen-24>", line 2, in broadcast_binary_op
  File "/Users/test/.virtualenvs/nnvm/lib/python3.6/site-packages/tvm-0.1.0-py3.6-macosx-10.13-x86_64.egg/tvm/tag.py", line 33, in tagged_fdecl
    return func(*args, **kwargs)
  File "/Users/test/.virtualenvs/nnvm/lib/python3.6/site-packages/topi-0.1.0-py3.6.egg/topi/broadcast.py", line 147, in broadcast_binary_op
    ret_shape = _get_binary_op_bcast_shape(get_const_tuple(lhs.shape), get_const_tuple(rhs.shape))
  File "/Users/test/.virtualenvs/nnvm/lib/python3.6/site-packages/topi-0.1.0-py3.6.egg/topi/util.py", line 63, in get_const_tuple
    raise ValueError("Element of input tuple should be const int")
ValueError: Element of input tuple should be const int
```

**Comment by masahi** [comment]
what happens if you remove upsampling? if this is upsampling issue it's on me.

**Comment by thefiddler** [comment]
If I remove the upsampling it works:
```python
from keras.layers import *
from keras.models import Model

x = input = Input((32, 32, 1))
r = Conv2D(2, (3, 3), strides=(2, 2), padding="valid")(x)
x = Conv2D(2, (3, 3), strides=(2, 2), padding="valid")(x)
x = add([x, r])
x = Conv2D(1, (1, 1))(x)
model = keras.models.Model(input, x)

verify_keras_frontend(model)
```

**Comment by masahi** [comment]
@thefiddler what happens if you remove this line?
https://github.com/dmlc/nnvm/blob/master/python/nnvm/top/nn.py#L267

**Comment by tqchen** [comment]
It should be objective

**Comment by tqchen** [comment]
Sorry INJECTIVE

**Comment by thefiddler** [comment]
@masahi commenting out that line fixes the crash.

**Comment by masahi** [comment]
hmm, with OpPattern.INJECTIVE I'm still getting the same error.
Only OPAQUE works here.

**Comment by masahi** [comment]
@thefiddler what is the shape of x and r at
```
x = add([x, r])
```
?
I don't understand why broadcast is called here.

**Comment by tqchen** [comment]
by default every add is broadcast add. 

I think the error could due to the fact that https://github.com/dmlc/tvm/blob/master/topi/python/topi/nn/upsampling.py#L24  multiples integer with float so that is no longer Int

**Comment by masahi** [comment]
yes I found the cause of the error
adding util.simplify fixed the issue.

```
    out_height = util.simplify(height * scale)
    out_width = util.simplify(width * scale)
```

**Comment by tqchen** [comment]
OK, I think it is instead the problem of get_const_tuple https://github.com/dmlc/tvm/blob/master/topi/python/topi/util.py#L61

It should call get_const_int to eagerly simplify things when necessary @masahi can you submit a PR?

**Comment by tqchen** [comment]
Also the upsampling should be INJECTIVE

**Comment by masahi** [comment]
ok
