### ISSUE TITLE
Unable to build ONNX model using NNVM

### ISSUE THREAD

**Issue by Mani-Sadhasivam** [dmlc/nnvm#336]
Hello,

I have a Caffe2 model exported to ONNX format using the below instructions:
https://github.com/onnx/tutorials/blob/master/tutorials/Caffe2OnnxExport.ipynb

When I try to build this model using NNVM I'm getting the below error:
https://pastebin.ubuntu.com/26459575/

Below commands are used to build the model:
```
onnx_graph = onnx.load('sqeezenet.onnx')
sym, params = nnvm.frontend.from_onnx(onnx_graph)
```
The same commands works well for the `super_resolution` model

**Comment by PENGUINLIONG** [comment]
It seems your NNVM is outdated. Could you try the latest version (cloned from the master branch) and see if it helps?

**Comment by Mani-Sadhasivam** [comment]
Rebasing to latest commit doesn't solve the issue :(

Error Log: https://pastebin.ubuntu.com/26481727/

**Comment by srkreddy1238** [comment]
Can you print and see check the operator name in [onnx.py](https://github.com/dmlc/nnvm/blob/c3cfe0ae4e9c2f2d4c4004666fd17b3c11d1efb8/python/nnvm/frontend/onnx.py#L487) ??

Siva

**Comment by Mani-Sadhasivam** [comment]
Operator name: Conv

**Comment by srkreddy1238** [comment]
Looks like some extra attributes from mxnet for Conv which is not addressed from frontend.

Try printing [attrs](https://github.com/dmlc/nnvm/blob/c3cfe0ae4e9c2f2d4c4004666fd17b3c11d1efb8/python/nnvm/frontend/onnx.py#L87) for super resolution and your model.


Siva

**Comment by srkreddy1238** [comment]
@Mani-Sadhasivam 

Try https://github.com/dmlc/nnvm/pull/345

Siva

**Comment by Mani-Sadhasivam** [comment]
@srkreddy1238 No luck :(

sqeezenet params: `{u'strides': (2L, 2L), u'pads': (0L, 0L, 0L, 0L), u'kernel_shape': (3L, 3L)}`

super_resolution params: `{u'dilations': (1L, 1L), u'strides': (1L, 1L), u'pads': (2L, 2L, 2L, 2L), u'group': 1L, u'kernel_shape': (5L, 5L)}`

**Comment by srkreddy1238** [comment]
Pls share more details on this error.

I see the graph is generated as below.

```
Graph(%input_0,
      %param_0,
      %param_1,
      %param_2,
      %param_3,
      %param_4,
      %param_5,
      %param_6,
      %param_7,
      %param_8,
      %param_9,
      %param_10,
      %param_11,
      %param_12,
      %param_13,
      %param_14,
      %param_15,
      %param_16,
      %param_17,
      %param_18,
      %param_19,
      %param_20,
      %param_21,
      %param_22,
      %param_23,
      %param_24,
      %param_25,
      %param_26,
      %param_27,
      %param_28,
      %param_29,
      %param_30,
      %param_31,
      %param_32,
      %param_33,
      %param_34,
      %param_35,
      %param_36,
      %param_37,
      %param_38,
      %param_39,
      %param_40,
      %param_41,
      %param_42,
      %param_43,
      %param_44,
      %param_45,
      %param_46,
      %param_47,
      %param_48,
      %param_49,
      %param_50,
      %param_51) {
  %3 = conv2d(%input_0, %param_0, %param_1, use_bias='True', channels='64', strides='(2, 2)', kernel_size='(3, 3)', padding='(0, 0)')
  %4 = relu(%3)
  %5 = max_pool2d(%4, ceil_mode='False', pool_size='(3, 3)', strides='(2, 2)', padding='(0, 0)')
  %8 = conv2d(%5, %param_2, %param_3, use_bias='True', channels='16', strides='(1, 1)', kernel_size='(1, 1)', padding='(0, 0)')
  %9 = relu(%8)
  %12 = conv2d(%9, %param_4, %param_5, use_bias='True', channels='64', strides='(1, 1)', kernel_size='(1, 1)', padding='(0, 0)')
  %13 = relu(%12)
  %16 = conv2d(%9, %param_6, %param_7, use_bias='True', channels='64', strides='(1, 1)', kernel_size='(3, 3)', padding='(1, 1)')
  %17 = relu(%16)
  %18 = concatenate(%13, %17)
  %21 = conv2d(%18, %param_8, %param_9, use_bias='True', channels='16', strides='(1, 1)', kernel_size='(1, 1)', padding='(0, 0)')
  %22 = relu(%21)
  %25 = conv2d(%22, %param_10, %param_11, use_bias='True', channels='64', strides='(1, 1)', kernel_size='(1, 1)', padding='(0, 0)')
  %26 = relu(%25)
  %29 = conv2d(%22, %param_12, %param_13, use_bias='True', channels='64', strides='(1, 1)', kernel_size='(3, 3)', padding='(1, 1)')
  %30 = relu(%29)
  %31 = concatenate(%26, %30)
  %32 = max_pool2d(%31, ceil_mode='False', pool_size='(3, 3)', strides='(2, 2)', padding='(0, 0)')
  %35 = conv2d(%32, %param_14, %param_15, use_bias='True', channels='32', strides='(1, 1)', kernel_size='(1, 1)', padding='(0, 0)')
  %36 = relu(%35)
  %39 = conv2d(%36, %param_16, %param_17, use_bias='True', channels='128', strides='(1, 1)', kernel_size='(1, 1)', padding='(0, 0)')
  %40 = relu(%39)
  %43 = conv2d(%36, %param_18, %param_19, use_bias='True', channels='128', strides='(1, 1)', kernel_size='(3, 3)', padding='(1, 1)')
  %44 = relu(%43)
  %45 = concatenate(%40, %44)
  %48 = conv2d(%45, %param_20, %param_21, use_bias='True', channels='32', strides='(1, 1)', kernel_size='(1, 1)', padding='(0, 0)')
  %49 = relu(%48)
  %52 = conv2d(%49, %param_22, %param_23, use_bias='True', channels='128', strides='(1, 1)', kernel_size='(1, 1)', padding='(0, 0)')
  %53 = relu(%52)
  %56 = conv2d(%49, %param_24, %param_25, use_bias='True', channels='128', strides='(1, 1)', kernel_size='(3, 3)', padding='(1, 1)')
  %57 = relu(%56)
  %58 = concatenate(%53, %57)
  %59 = max_pool2d(%58, ceil_mode='False', pool_size='(3, 3)', strides='(2, 2)', padding='(0, 0)')
  %62 = conv2d(%59, %param_26, %param_27, use_bias='True', channels='48', strides='(1, 1)', kernel_size='(1, 1)', padding='(0, 0)')
  %63 = relu(%62)
  %66 = conv2d(%63, %param_28, %param_29, use_bias='True', channels='192', strides='(1, 1)', kernel_size='(1, 1)', padding='(0, 0)')
  %67 = relu(%66)
  %70 = conv2d(%63, %param_30, %param_31, use_bias='True', channels='192', strides='(1, 1)', kernel_size='(3, 3)', padding='(1, 1)')
  %71 = relu(%70)
  %72 = concatenate(%67, %71)
  %75 = conv2d(%72, %param_32, %param_33, use_bias='True', channels='48', strides='(1, 1)', kernel_size='(1, 1)', padding='(0, 0)')
  %76 = relu(%75)
  %79 = conv2d(%76, %param_34, %param_35, use_bias='True', channels='192', strides='(1, 1)', kernel_size='(1, 1)', padding='(0, 0)')
  %80 = relu(%79)
  %83 = conv2d(%76, %param_36, %param_37, use_bias='True', channels='192', strides='(1, 1)', kernel_size='(3, 3)', padding='(1, 1)')
  %84 = relu(%83)
  %85 = concatenate(%80, %84)
  %88 = conv2d(%85, %param_38, %param_39, use_bias='True', channels='64', strides='(1, 1)', kernel_size='(1, 1)', padding='(0, 0)')
  %89 = relu(%88)
  %92 = conv2d(%89, %param_40, %param_41, use_bias='True', channels='256', strides='(1, 1)', kernel_size='(1, 1)', padding='(0, 0)')
  %93 = relu(%92)
  %96 = conv2d(%89, %param_42, %param_43, use_bias='True', channels='256', strides='(1, 1)', kernel_size='(3, 3)', padding='(1, 1)')
  %97 = relu(%96)
  %98 = concatenate(%93, %97)
  %101 = conv2d(%98, %param_44, %param_45, use_bias='True', channels='64', strides='(1, 1)', kernel_size='(1, 1)', padding='(0, 0)')
  %102 = relu(%101)
  %105 = conv2d(%102, %param_46, %param_47, use_bias='True', channels='256', strides='(1, 1)', kernel_size='(1, 1)', padding='(0, 0)')
  %106 = relu(%105)
  %109 = conv2d(%102, %param_48, %param_49, use_bias='True', channels='256', strides='(1, 1)', kernel_size='(3, 3)', padding='(1, 1)')
  %110 = relu(%109)
  %111 = concatenate(%106, %110)
  %114 = conv2d(%111, %param_50, %param_51, use_bias='True', channels='1000', strides='(1, 1)', kernel_size='(1, 1)', padding='(0, 0)')
  %115 = relu(%114)
  %116 = global_avg_pool2d(%115)
  %117 = softmax(%116)
  ret %117
}
```

The new error now I see is about 3D softmax, which is not supported as of now.

```
Traceback (most recent call last):
  File "from_onnx.py", line 85, in <module>
    graph, lib, params = nnvm.compiler.build(sym, target, shape_dict, params=params)
  File "/home/srk/.local/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/compiler/build_module.py", line 295, in build
    graph = graph.apply("GraphFuseCompile")
  File "/home/srk/.local/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/graph.py", line 235, in apply
    check_call(_LIB.NNGraphApplyPasses(self.handle, npass, cpass, ctypes.byref(ghandle)))
  File "/home/srk/.local/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/_base.py", line 72, in check_call
    raise NNVMError(py_str(_LIB.NNGetLastError()))
nnvm._base.NNVMError: TVMCall CFunc Error:
Traceback (most recent call last):
  File "/home/srk/.local/lib/python3.6/site-packages/tvm-0.1.0-py3.6-linux-x86_64.egg/tvm/_ffi/_ctypes/function.py", line 54, in cfun
    rv = local_pyfunc(*pyargs)
  File "/home/srk/.local/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/top/nn.py", line 65, in compute_softmax
    return topi.nn.softmax(inputs[0])
  File "<decorator-gen-36>", line 2, in softmax
  File "/home/srk/.local/lib/python3.6/site-packages/tvm-0.1.0-py3.6-linux-x86_64.egg/tvm/tag.py", line 33, in tagged_fdecl
    return func(*args, **kwargs)
  File "/home/srk/.local/lib/python3.6/site-packages/topi-0.1.0-py3.6.egg/topi/nn/softmax.py", line 20, in softmax
    assert len(x.shape) == 2, "only support 2-dim softmax"
AssertionError: only support 2-dim softmax

```

Not sure what is the status of softmax-3d support.


Siva

**Comment by Mani-Sadhasivam** [comment]
@srkreddy1238 That's great to hear :)

Looking forward to the patch. Thanks!

**Comment by srkreddy1238** [comment]
Yes, I did as per the above instructions.

**Comment by srkreddy1238** [comment]
@Mani-Sadhasivam 

https://github.com/dmlc/nnvm/issues/360

Reverted above flatten node injection patch in interest of this new patch.

You could check the squeezenet functionality now. 

Siva
