### ISSUE TITLE
[TVM Upgrade]

### ISSUE THREAD

**Issue by srkreddy1238** [dmlc/nnvm#350]
Below error with TVM master branch on top or NNVM master.

```
Traceback (most recent call last):
  File "get_started.py", line 8, in <module>
    import nnvm.compiler
  File "/home/srk/.local/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/__init__.py", line 6, in <module>
    from . import _base
  File "/home/srk/.local/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/_base.py", line 47, in <module>
    _LIB = _load_lib()
  File "/home/srk/.local/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/_base.py", line 39, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/srk/.local/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/libnnvm_compiler.so: undefined symbol: _ZN6Halide4ExprC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

```

Siva

**Comment by srkreddy1238** [comment]
I see it may be due to https://github.com/dmlc/nnvm/pull/349

Siva
