### ISSUE TITLE
speed test for nnvm through squeezenet

### ISSUE THREAD

**Issue by wl3b10s** [dmlc/nnvm#366]
i test standard squeezenet v1.1 on 8xA53 ubuntu 16.04.

my implementation:
1. baidu ncnn
2. nnvm+tvm
both of them is compiled natively on device. and the time test result show that nnvm is the slower.

frame test time result:
1. baidu ncnn 80ms
2. nnvm + tvm: 360ms (600ms with default compile, change  nnvm.compiler.build_config and tvm.build_config can speed up to 360ms)

so. is there some tips for optimize speed for usage of nnvm? thanks.

**Comment by tqchen** [comment]
cc @ZihengJiang  Try to reuse the raspberry pi configs, this means enable target.rasp tag like in here https://github.com/dmlc/nnvm/blob/master/examples/benchmark/rasp_imagenet_bench.py#L44

**Comment by wl3b10s** [comment]
follow @tqchen  advice, i change the code in from_coreml.py to "
with nnvm.compiler.build_config(opt_level=2):
  graph, lib, params = nnvm.compiler.build(sym, tvm.target.rasp(), shape_dict, params=params)  
"

but got runtime error below:
"
Traceback (most recent call last):
  File "from_coreml.py", line 76, in <module>
    graph, lib, params = nnvm.compiler.build(sym, tvm.target.rasp(), shape_dict, params=params)
  File "/root/.local/lib/python2.7/site-packages/nnvm-0.8.0-py2.7.egg/nnvm/compiler/build_module.py", line 251, in build
    graph = graph.apply("GraphFusePartition").apply("GraphFuseCompile")
  File "/root/.local/lib/python2.7/site-packages/nnvm-0.8.0-py2.7.egg/nnvm/graph.py", line 234, in apply
    check_call(_LIB.NNGraphApplyPasses(self.handle, npass, cpass, ctypes.byref(ghandle)))
  File "/root/.local/lib/python2.7/site-packages/nnvm-0.8.0-py2.7.egg/nnvm/_base.py", line 72, in check_call
    raise NNVMError(py_str(_LIB.NNGetLastError()))
nnvm._base.NNVMError: TVMCall CFunc Error:
Traceback (most recent call last):
  File "/root/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-aarch64.egg/tvm/_ffi/_ctypes/function.py", line 54, in cfun
    rv = local_pyfunc(*pyargs)
  File "/root/.local/lib/python2.7/site-packages/nnvm-0.8.0-py2.7.egg/nnvm/top/nn.py", line 123, in compute_conv2d
    out = topi.nn.conv2d(inputs[0], inputs[1], strides, padding)
  File "<decorator-gen-27>", line 2, in conv2d
  File "/root/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-aarch64.egg/tvm/target.py", line 225, in dispatch_func
    return dispatch_dict[k](*args, **kwargs)
  File "/root/.local/lib/python2.7/site-packages/topi-0.1.0-py2.7.egg/topi/rasp/conv2d.py", line 56, in _declaration_conv2d
    sch = _get_schedule(wkl)
  File "<decorator-gen-28>", line 2, in _get_schedule
  File "/root/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-aarch64.egg/tvm/target.py", line 225, in dispatch_func
    return dispatch_dict[k](*args, **kwargs)
  File "/root/.local/lib/python2.7/site-packages/topi-0.1.0-py2.7.egg/topi/rasp/conv2d.py", line 45, in _schedule_conv2d
    raise ValueError("no schedule for such workload: {}".format(wkl))
ValueError: no schedule for such workload: Workload(in_dtype='float32', out_dtype='float32', height=227, width=227, in_filter=3, out_filter=64, hkernel=3, wkernel=3, hpad=0, wpad=0, hstride=2, wstride=2)
"

whether this is becsuse hardware not compatable or that param optimize used in squeezenet is not implemented in default rasp optimization??

thanks.

**Comment by tqchen** [comment]
it was due to the specific configuration not yet implemented in the rasp optimization. For now, you can try resnet or mobilenet with typical input like 224

**Comment by wl3b10s** [comment]
thanks@tqchen
