### ISSUE TITLE
Execute forward and gradient graph

### ISSUE THREAD

**Issue by AtuNuka** [dmlc/nnvm#379]
Hi,

Could you help me add the implementation for neural-network training to NNVM/TVM?
Before starting that implementation, I wrote a small script attached below to see if I understand well how to build and run a compute-graph by using NNVM/TVM.
Because I want the script to train a neural network, the graph has both forward and gradient paths.
But an exception is raised while executing ```runtime.create(graph, lib, ctx)``` .

From ```graph.symbol``` output, the compute-graph seems to be built correctly. (But I'm not sure that the built compute-graph is correct or not.)

From my little investigation of TVM python code, I noticed that ```tvm.contrib.graph_runtime.create()``` only supports the forward compute-graph execution.
Do I need to implement an additional code the like ```runtime.create()```, if I want to execute a compute-graph for training by using NNVM/TVM?

#### Environment

* Windows 10 Pro (64bit)
* Python 3.5 (Anaconda)
* Commit ID
   * NNVM: dd4f6a9f95a45068252b2f32f7e07d1b07596740
   * TVM: 3a91764ec919b7a0034e104c7fac40ed5a840d12

#### Code

```python
import nnvm
import tvm
import nnvm.symbol as sym
import numpy as np
import nnvm.testing

from tvm.contrib import graph_runtime as runtime


def build_train_graph(net, target, dshape, params):
    # optimization is not good for training
    with nnvm.compiler.build_config(opt_level=0):

        # build infer graph
        graph_infer, lib, params = nnvm.compiler.build(net, target, shape={"data": dshape}, params=params)

        # build train graph
        graph_infer._set_symbol_list_attr("grad_ys", net)
        graph_infer._set_symbol_list_attr("grad_xs", net.list_input_variables())
        ny = len(net.list_output_names())
        graph_infer._set_symbol_list_attr("grad_ys_out_grad", [sym.ones_like(net[i]) for i in range(ny)])
        graph = graph_infer.apply("Gradient")

    return graph, lib, params


def main():
    out_channels = 16
    data = sym.Variable(name="data")
    net = sym.conv2d(data=data, kernel_size=(3, 3), channels=out_channels, padding=(1, 1), use_bias=False)

    batch_size = 1
    dshape = (batch_size, 3, 224, 224)

    net, params = nnvm.testing.utils.create_workload(net, batch_size, dshape[1:])

    target = "opencl"

    graph, lib, params = build_train_graph(net, target, dshape, params)

    for i, s in enumerate(graph.symbol):
        print("=== Symbol ({}) ===".format(i))
        print(s.debug_str())

    ctx = tvm.context(target, 0)
    data = np.random.uniform(-1, 1, size=dshape).astype("float32")
    module = runtime.create(graph, lib, ctx)
    module.set_input(**params)
    module.set_input("data", data)
    module.run()
    out_shape = (batch_size, out_channels, 224, 224)
    out = module.get_output(0, tvm.nd.empty(out_shape))
    out_data = out.asnumpy()
    print(out_data)


if __name__ == "__main__":
    try:
        main()
    except nnvm.NNVMError as e:
        print(e)

```

#### Output

```bash
=== Symbol (0) ===
Symbol Outputs:
	output[0]=conv2d0_grad(0)
Variable:data
Variable:conv2d0_weight
--------------------
Op:conv2d, Name=conv2d0
Inputs:
	arg[0]=data(0) version=0
	arg[1]=conv2d0_weight(0) version=0
Attrs:
	channels=16
	kernel_size=(3, 3)
	padding=(1, 1)
	use_bias=False
--------------------
Op:ones_like, Name=ones_like0
Inputs:
	arg[0]=conv2d0(0)
--------------------
Op:_conv2d_grad, Name=conv2d0_grad
Inputs:
	arg[0]=ones_like0(0)
	arg[1]=data(0) version=0
	arg[2]=conv2d0_weight(0) version=0
Attrs:
	channels=16
	kernel_size=(3, 3)
	padding=(1, 1)
	use_bias=False

=== Symbol (1) ===
Symbol Outputs:
	output[0]=conv2d0_grad(1)
Variable:data
Variable:conv2d0_weight
--------------------
Op:conv2d, Name=conv2d0
Inputs:
	arg[0]=data(0) version=0
	arg[1]=conv2d0_weight(0) version=0
Attrs:
	channels=16
	kernel_size=(3, 3)
	padding=(1, 1)
	use_bias=False
--------------------
Op:ones_like, Name=ones_like0
Inputs:
	arg[0]=conv2d0(0)
--------------------
Op:_conv2d_grad, Name=conv2d0_grad
Inputs:
	arg[0]=ones_like0(0)
	arg[1]=data(0) version=0
	arg[2]=conv2d0_weight(0) version=0
Attrs:
	channels=16
	kernel_size=(3, 3)
	padding=(1, 1)
	use_bias=False

Traceback (most recent call last):
  File "C:/Users/nuka/PycharmProjects/nnvm_build/train_route_spike.py", line 60, in <module>
    main()
  File "C:/Users/nuka/PycharmProjects/nnvm_build/train_route_spike.py", line 48, in main
    module = runtime.create(graph, lib, ctx)
  File "C:\Users\nuka\AppData\Local\Continuum\anaconda3\envs\nnvm_build\lib\site-packages\tvm-0.1.0-py3.5-win-amd64.egg\tvm\contrib\graph_runtime.py", line 44, in create
    return GraphModule(fcreate(graph_json_str, libmod, device_type, device_id), ctx)
  File "C:\Users\nuka\AppData\Local\Continuum\anaconda3\envs\nnvm_build\lib\site-packages\tvm-0.1.0-py3.5-win-amd64.egg\tvm\_ffi\_ctypes\function.py", line 183, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "C:\Users\nuka\AppData\Local\Continuum\anaconda3\envs\nnvm_build\lib\site-packages\tvm-0.1.0-py3.5-win-amd64.egg\tvm\_ffi\base.py", line 62, in check_call
    raise TVMError(py_str(_LIB.TVMGetLastError()))
tvm._ffi.base.TVMError: [11:03:41] C:\Users\nuka\workspace\dev\git_repo_local\nnvm\tvm\src\runtime\graph\graph_runtime.cc:224: Check failed: bitmask == 1|2|4|8 (0 vs. 15) invalid format
```

Thanks

**Comment by AtuNuka** [comment]
I could solve this issue by below step.

* Call ```nnvm.compiler.build()``` **again** after applying Gradient pass
* Add own gradient operators (ones_like, _conv2d_grad) by using the decorator ```@reg.register_compute``` and ```@reg.register_compute```

After these revision, I could execute the computation-graph for training.



#### Example code (Build a gradient graph)

```python
def build_train_graph(net, target, dshape, params):
    # optimization is not good for training
    with nnvm.compiler.build_config(opt_level=0):

        # build infer graph
        graph_infer, _, params = nnvm.compiler.build(net, target, shape={"data": dshape}, params=params)

        # build train graph
        graph_infer._set_symbol_list_attr("grad_ys", net)
        graph_infer._set_symbol_list_attr("grad_xs", net.list_input_variables())
        ny = len(net.list_output_names())
        graph_infer._set_symbol_list_attr("grad_ys_out_grad", [sym.ones_like(net[i]) for i in range(ny)])
        graph = graph_infer.apply("Gradient")

        # need to call nnvm.compiler.build() again
        graph, lib, params = nnvm.compiler.build(graph, target, shape={"data": dshape}, params=params)

    return graph, lib, params
```


#### Example code (Add ones_like operator)

```python
# ones like
@reg.register_compute("ones_like")
def compute_ones_like(attrs, inputs, _):
    print(inputs[0].shape)
    return tvm.compute(inputs[0].shape, lambda *i: tvm.const(1, 'float32'))


def _schedule_generic(outs):
    outs = [outs] if isinstance(outs, tvm.tensor.Tensor) else outs
    s = tvm.create_schedule([x.op for x in outs])
    tvm.schedule.AutoInlineInjective(s)
    for out in outs:
        if isinstance(out.op, tvm.tensor.ExternOp):
            continue
        _schedule_output(out.op, s)

    return s


def _schedule_output(op, sch):
    x = op.output(0)
    fused = sch[x].fuse(*sch[x].op.axis)
    num_thread = tvm.target.current_target(allow_none=False).max_num_threads
    bx, tx = sch[x].split(fused, factor=num_thread)
    sch[x].bind(bx, tvm.thread_axis("blockIdx.x"))
    sch[x].bind(tx, tvm.thread_axis("threadIdx.x"))
    return sch


@reg.register_schedule("ones_like")
def schedule_ones_like(_, outs, target):
    return _schedule_generic(outs)

reg.register_pattern("ones_like", OpPattern.ELEMWISE)
```


Sorry for tainting the issue.

**Comment by wonjeon** [comment]
Is this change enabling backward-path gradient computation for training already merged to the main repo?
Is there any example of training models in the main repo? Thanks.

**Comment by AtuNuka** [comment]
> Is this change enabling backward-path gradient computation for training already merged to the main repo?

No. This is a code for my personal use.

> Is there any example of training models in the main repo?

NNVM has an ability to construct the backward-computation graph from forward-computation graph by applying Gradient pass implemented in [nnvm/src/pass/gradient.cc](https://github.com/dmlc/tvm/blob/master/nnvm/src/pass/gradient.cc).

But as far as I know, TVM has no implementation of backward computation.
So, we can make the backward-computation graph, but can't train with NNVM/TVM.

**Comment by wonjeon** [comment]
Thanks for your response. Then, how hard is it to add backward computation for each op in TVM? What kind other changes do I have to make in TVM in order to add backward computation?

**Comment by AtuNuka** [comment]
You need to all gradient operations you may use to TVM.
Sometimes you need to add new operation to NNVM.
