### ISSUE TITLE
openCL issues with tutorial

### ISSUE THREAD

**Issue by Bryanscott13** [dmlc/nnvm#395]
```
-------compute graph-------
Graph(%x, %y) {
  %2 = sqrt(%y)
  %3 = elemwise_add(%x, %2)
  ret %3
}
[13:30:37] src/runtime/opencl/opencl_device_api.cc:197: Initialize OpenCL platform 'Apple'
[13:30:37] src/runtime/opencl/opencl_device_api.cc:222: opencl(0)='Intel(R) HD Graphics 630' cl_device_id=0x1024500
[13:30:37] src/runtime/opencl/opencl_device_api.cc:222: opencl(1)='AMD Radeon Pro 560 Compute Engine' cl_device_id=0x1021c00
-------deploy graph-------
Graph(%x, %y) {
  %2 = tvm_op(%x, %y, num_outputs='1', num_inputs='2', func_name='fuse_sqrt_elemwise_add', flatten_data='1')
  ret %2
}
graph_attr_keys = [storage_id, shape, dtype, dltype]

-------deploy library-------
__kernel void fuse_sqrt_elemwise_add__kernel0(__global float* restrict tensor, __global float* restrict input1, __global float* restrict input0) {
  if (((int)get_local_id(0)) < 4) {
    tensor[((int)get_local_id(0))] = (input1[((int)get_local_id(0))] + sqrt(input0[((int)get_local_id(0))]));
  }
}


[3. 4. 5. 6.]
Traceback (most recent call last):
  File "get_started.py", line 107, in <module>
    compute_graph, target="opencl", shape={"x": shape}, params={"y": y_np})
  File "/usr/local/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/compiler/build_module.py", line 237, in build
    graph, params = precompute_prune(graph, params)
  File "/usr/local/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/compiler/build_module.py", line 330, in precompute_prune
    out_arrs = _run_graph(pre_graph, params)
  File "/usr/local/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/compiler/build_module.py", line 279, in _run_graph
    graph, libmod, _ = build(graph, target, shape, dtype)
  File "/usr/local/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/compiler/build_module.py", line 251, in build
    graph = graph.apply("GraphFusePartition").apply("GraphFuseCompile")
  File "/usr/local/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/graph.py", line 234, in apply
    check_call(_LIB.NNGraphApplyPasses(self.handle, npass, cpass, ctypes.byref(ghandle)))
  File "/usr/local/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/_base.py", line 72, in check_call
    raise NNVMError(py_str(_LIB.NNGetLastError()))
nnvm._base.NNVMError: TVMCall CFunc Error:
```

The first tutorial examples run fine, but I cannot figure out what is going on with the "Provide Model Parameters"

**Comment by Bryanscott13** [comment]
`tvm._ffi.base.TVMError: [15:41:48] src/codegen/codegen.cc:27: Check failed: bf != nullptr Target llvm is not enabled`

Why is it telling me LLVM is not enabled? I have modified the get_started.py to use the target as "opencl" and modified the TVM config.mk to "USE_OPENCL = 1"

**Comment by merrymercy** [comment]
Enable llvm by modifying these liens
https://github.com/dmlc/tvm/blob/1d6df5a187127f514ea48f6a8a74c77ff59c89f5/make/config.mk#L56-L60

**Comment by Bryanscott13** [comment]
`src/codegen/llvm/./llvm_common.h:10:10: fatal error: 'llvm/ExecutionEngine/MCJIT.h' file not found`

This is the error when I try running make after modifying the "config.mk" to "LLVM_CONFIG = llvm-config-6.0"

**Comment by Bryanscott13** [comment]
Thanks! I did have to specify the full path to llvm-config since I installed it using homebrew.
