### ISSUE TITLE
nvrtc: error: failed to load builtins

### ISSUE THREAD

**Issue by zhangxinqian** [dmlc/nnvm#408]
Hi, I'm running nnvm get start tutorial in nvidia jestson tx1 (arm cpu), but when running at nnvm.compiler.build I get the error  "TVMError: [12:49:51] src/codegen/build_cuda.cc:38: Check failed: compile_res == NVRTC_SUCCESS (7 vs. 0) nvrtc: error: failed to load builtins". The full error stack is below:

Traceback (most recent call last):
  File "get_start.py", line 12, in <module>
    deploy_graph, lib, params = nnvm.compiler.build(compute_graph, target="cuda", shape={"x": shape}, dtype="float32")
  File "/home/ubuntu/.local/lib/python2.7/site-packages/nnvm-0.8.0-py2.7.egg/nnvm/compiler/build_module.py", line 251, in build
    graph = graph.apply("GraphFusePartition").apply("GraphFuseCompile")
  File "/home/ubuntu/.local/lib/python2.7/site-packages/nnvm-0.8.0-py2.7.egg/nnvm/graph.py", line 234, in apply
    check_call(_LIB.NNGraphApplyPasses(self.handle, npass, cpass, ctypes.byref(ghandle)))
  File "/home/ubuntu/.local/lib/python2.7/site-packages/nnvm-0.8.0-py2.7.egg/nnvm/_base.py", line 72, in check_call
    raise NNVMError(py_str(_LIB.NNGetLastError()))
nnvm._base.NNVMError: TVMCall CFunc Error:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-aarch64.egg/tvm/_ffi/_ctypes/function.py", line 54, in cfun
    rv = local_pyfunc(*pyargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/nnvm-0.8.0-py2.7.egg/nnvm/compiler/build_module.py", line 119, in _build
    return tvm.build(funcs, target=target, target_host=target_host)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-aarch64.egg/tvm/build_module.py", line 449, in build
    mdev = codegen.build_module(fdevice, str(target_device))
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-aarch64.egg/tvm/codegen.py", line 20, in build_module
    return _Build(lowered_func, target)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-aarch64.egg/tvm/_ffi/function.py", line 255, in my_api_func
    return flocal(*args)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-aarch64.egg/tvm/_ffi/_ctypes/function.py", line 183, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tvm-0.1.0-py2.7-linux-aarch64.egg/tvm/_ffi/base.py", line 62, in check_call
    raise TVMError(py_str(_LIB.TVMGetLastError()))
TVMError: [12:49:51] src/codegen/build_cuda.cc:38: Check failed: compile_res == NVRTC_SUCCESS (7 vs. 0) nvrtc: error: failed to load builtins

I build the llvm, nnvm and tvm from source on arm. The cuda toolkit is version 8 and ubuntu version is 16.04. I'm sure libnvrtc.so and libnvrtc-builtins.so are in the $LD_LIBRARY_PATH. In addition,  I run it successfully by setting target = 'llvm' instead of target='cuda'. 
Can someone help me to fix it? Thanks.

**Comment by zhangxinqian** [comment]
Is it similar to https://github.com/apache/incubator-mxnet/pull/8406 and https://github.com/cupy/cupy/pull/687? If it is, then how can I set gpu arch option or compute capability to nvrtc in nnvm?

**Comment by tqchen** [comment]
I am not sure if it is an issue of TVM itself, one thing you could possibly do is is cross-compilation and RPC, so we only have to build a runtime on the ARM

**Comment by zhangxinqian** [comment]
@tqchen Thanks. I will try cross-compilation. But how can I change compiler in nnvm to build .so module that runs on Jetson platform

**Comment by zhangxinqian** [comment]
I set target='llvm --target=aarch64-linux-gnu', but an error occurs: tvm._ffi.base.TVMError: [16:34:12] src/codegen/llvm/llvm_common.cc:91: unknown option --target

**Comment by zhangxinqian** [comment]
sorry my bad. It should be target='llvm -target=aarch64-linux-gnu', not --target.

**Comment by zhangxinqian** [comment]
By cross-compilation, I can run it successfully on Jetson TX2 without RPC.

**Comment by fzuwill** [comment]
@zhangxinqian how to solve this problem? I successfully run the NVRTC demo. However, I run the get_started.py with the error "failed to load builtins". I add the absolute path of libnvrtc-builtins.so to TVM_LINKER_LIBS  and  TVM_RUNTIME_LINKER_LIBS in CMakeLists.txt. It still failed to run get_started.py with the same error.

**Comment by zhangxinqian** [comment]
@fzuwill Try cross compilation. You can see this example https://github.com/zhangxinqian/jetsontx2-cross-compilation-using-nnvm-and-tvm.
