### ISSUE TITLE
RK3399 MALI GPU RUN ERROR

### ISSUE THREAD

**Issue by daming5432** [dmlc/nnvm#442]
I want to run the coreml example in RK3399.  I use the target="llvm", this is ok. When I use the target="opencl" target_host="llvm", the build is ok, the running error is here:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/firefly/.local/lib/python2.7/site-packages/tvm-0.2.0-py2.7-linux-aarch64.egg/tvm/contrib/graph_runtime.py", line 113, in run
    self._run()
  File "/home/firefly/.local/lib/python2.7/site-packages/tvm-0.2.0-py2.7-linux-aarch64.egg/tvm/_ffi/_ctypes/function.py", line 183, in __call__
    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))
  File "/home/firefly/.local/lib/python2.7/site-packages/tvm-0.2.0-py2.7-linux-aarch64.egg/tvm/_ffi/base.py", line 66, in check_call
    raise TVMError(py_str(_LIB.TVMGetLastError()))
tvm._ffi.base.TVMError: [02:51:40] src/runtime/module_util.cc:52: Check failed: ret == 0 (-1 vs. 0) [02:51:40] src/runtime/opencl/opencl_module.cc:223: Check failed: e == CL_SUCCESS OpenCL Error, code=-5: CL_OUT_OF_RESOURCES

**Comment by daming5432** [comment]
When I use the target = "tvm.target.mali()", it can run, but the result is wrong. Is it that I cannot use the coreml in RK3399's GPU?

**Comment by tqchen** [comment]
please use https://discuss.tvmlang.org/ for general discussions. It is correct to use tvm.target.mali() when you are targeting mali gpus
