### ISSUE TITLE
Darknet tutorial front end issues

### ISSUE THREAD

**Issue by Bryanscott13** [dmlc/nnvm#443]
```
File yolo.cfg exists, skip.
File yolo.weights exists, skip.
File libdarknet.so exists, skip.
Traceback (most recent call last):
  File "from_darknet.py", line 134, in <module>
    darknet_lib = __darknetffi__.dlopen('./' + darknet_lib)
  File "/usr/local/lib/python3.6/site-packages/cffi/api.py", line 141, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/usr/local/lib/python3.6/site-packages/cffi/api.py", line 802, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/usr/local/lib/python3.6/site-packages/cffi/api.py", line 797, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library './libdarknet.so': dlopen(./libdarknet.so, 2): no suitable image found.  Did find:
	./libdarknet.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/bryanscott/nnvm/nnvm/tutorials/libdarknet.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00.  Additionally, ctypes.util.find_library() did not manage to locate a library called './libdarknet.so'
```

I can't get the tutorial for darknet to run, I have installed everything, the checks pass for "libdarknet.so" but then it tells me It cannot locate the library. I am on MacOSX

**Comment by Bryanscott13** [comment]
I also tried using the libdarknet.a and darknet from the webpage, and get the same error

**Comment by PariksheetPinjari909** [comment]
@Bryanscott13  the issue is the lib mismatch for MacOSX.
you can download code from https://github.com/siju-samuel/darknet.git and do a make
use that lib

**Comment by Bryanscott13** [comment]
Thanks, that fixed the issue.
