### ISSUE TITLE
RuntimeError: cannot dereference null pointer from cdata 'float *' 

### ISSUE THREAD

**Issue by Bryanscott13** [dmlc/nnvm#444]
I have tried running the darknet test from the test folder as well as the darknet tutorial but am getting the same error in both cases. 

Executing the following lines:
```
dtype = 'float32' 
batch_size = 1
print("Converting darknet to nnvm symbols...")
sym, params = nnvm.frontend.darknet.from_darknet(net, dtype)
```

But I get the following error:
```
Loading weights from ./yolo.weights...Done!
Converting darknet to nnvm symbols...
Traceback (most recent call last):
  File "from_darknet.py", line 141, in <module>
    sym, params = nnvm.frontend.darknet.from_darknet(net, dtype)
  File "/usr/local/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/frontend/darknet.py", line 643, in from_darknet
    return _from_darknet(net, dtype)
  File "/usr/local/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/frontend/darknet.py", line 617, in _from_darknet
    _get_darknet_params(net.layers[i], layer_name, tvmparams, dtype)
  File "/usr/local/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/frontend/darknet.py", line 566, in _get_darknet_params
    _get_convolution_weights(layer, opname, tvmparams, dtype)
  File "/usr/local/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/frontend/darknet.py", line 414, in _get_convolution_weights
    biases = _read_memory_buffer((layer.n, ), layer.biases, dtype)
  File "/usr/local/lib/python3.6/site-packages/nnvm-0.8.0-py3.6.egg/nnvm/frontend/darknet.py", line 397, in _read_memory_buffer
    data_np[i] = data[i]
RuntimeError: cannot dereference null pointer from cdata 'float *'
```

**Comment by PariksheetPinjari909** [comment]
I will check locally on Mac and get back to you.

**Comment by tqchen** [comment]
please move general community questions to https://discuss.tvmlang.org/
