### ISSUE TITLE
symbol does not support using the same name

### ISSUE THREAD

**Issue by kazum** [dmlc/nnvm#508]
```
import nnvm
import nnvm.symbol as sym

data1 = sym.Variable(name="data1")
data2 = sym.Variable(name="data2")
c1 = sym.conv2d(data=data1, kernel_size=(3,3), channels=1, name="conv")
c2 = sym.conv2d(data=data2, kernel_size=(3,3), channels=1, name="conv")
x = sym.elemwise_add(c1, c2)
g = nnvm.graph.create(x)

print g.ir()
```

The above code generates an invalid IR:
```
Graph(%data1,
      %conv_weight,
      %conv_bias,
      %data2,
      %conv_weight,
      %conv_bias) {
  %3 = conv2d(%data1, %conv_weight, %conv_bias, kernel_size='(3, 3)', channels='1')
  %7 = conv2d(%data2, %conv_weight, %conv_bias, kernel_size='(3, 3)', channels='1')
  %8 = elemwise_add(%3, %7)
  ret %8
}
```

What I expected is as follows:
```
Graph(%data1,
      %conv_weight,
      %conv_bias,
      %data2) {
  %3 = conv2d(%data1, %conv_weight, %conv_bias, kernel_size='(3, 3)', channels='1')
  %7 = conv2d(%data2, %conv_weight, %conv_bias, kernel_size='(3, 3)', channels='1')
  %8 = elemwise_add(%3, %7)
  ret %8
}
```

**Comment by srkreddy1238** [comment]
The expectation may be wrong as it's two different conv operations we tried to create.
and 
The build should return error on duplicate names we have here.

**Comment by kazum** [comment]
@srkreddy1238 Thanks for your comment.

With the build, I got the following error:
```
Traceback (most recent call last):
  File "error/conv.py", line 13, in <module>
    nnvm.compiler.build(g, target="llvm", params={"conv_weight": np.zeros((1,3,3,3)).astype("float32")})
  File "/Users/kazutaka/git/nnvm/python/nnvm/compiler/build_module.py", line 275, in build
    graph, params = precompute_prune(graph, params)
  File "/Users/kazutaka/git/nnvm/python/nnvm/compiler/build_module.py", line 366, in precompute_prune
    graph = graph.apply("PrecomputePrune")
  File "/Users/kazutaka/git/nnvm/python/nnvm/graph.py", line 234, in apply
    check_call(_LIB.NNGraphApplyPasses(self.handle, npass, cpass, ctypes.byref(ghandle)))
  File "/Users/kazutaka/git/nnvm/python/nnvm/_base.py", line 75, in check_call
    raise NNVMError(py_str(_LIB.NNGetLastError()))
nnvm._base.NNVMError: [22:22:45] src/compiler/precompute_prune.cc:41: Check failed: !unique_name.count(var->attrs.name) no unique conv_weight
```
I think we can show a more user-friendly message to explain what is wrong.

**Comment by kazum** [comment]
The below code causes the same error `Check failed: !unique_name.count(var->attrs.name)`.
Is this also an unexpected usage of symbols?
```
import nnvm
import nnvm.symbol as sym
import numpy as np

data = sym.Variable(name="data", shape=(1,3,3,3))
param = sym.Variable(name="param")
x = sym.batch_norm(data=data, beta=param, moving_mean=param)
x = sym.batch_norm(data=x, beta=param)
g = nnvm.graph.create(x)

nnvm.compiler.build(g, target="llvm", params={"param": np.zeros((3,)).astype("float32")})
```

The strange thing is that the following code works without errors.
```
import nnvm
import nnvm.symbol as sym
import numpy as np

data = sym.Variable(name="data", shape=(1,3,3,3))
param = sym.Variable(name="param")
x = sym.batch_norm(data=data, beta=param)
x = sym.batch_norm(data=x, beta=param, moving_mean=param)
g = nnvm.graph.create(x)

nnvm.compiler.build(g, target="llvm", params={"param": np.zeros((3,)).astype("float32")})
```

**Comment by srkreddy1238** [comment]
@kazum  : Finally nailed it.

It's all due to version not considered while precompute prune pass.

https://github.com/dmlc/nnvm/pull/514
This change would maintains different copy of param while version is different.

**Comment by kazum** [comment]
Great, now build works as I expect.  Thanks.
