### ISSUE TITLE
Packaging nnvm for NixOS

### ISSUE THREAD

**Issue by grwlf** [dmlc/nnvm#519]
Hi! I am trying to write a package expression describing the build process of nnvm in Nix language. Actually, tvm and nnvm build steps already work (all addons are disabled), the problem appears when I try to build nnvm/python module.

The error is below:

```
nnvm (unittest.loader._FailedTest) ... ERROR
                                                                       
======================================================================        
ERROR: nnvm (unittest.loader._FailedTest)                                                               
----------------------------------------------------------------------                     
ImportError: Failed to import test module: nnvm
Traceback (most recent call last):                                  
  File "/nix/store/cwxxbpfz2i2j34f3sgmd6vdl6wv98c2s-python3-3.6.4/lib/python3.6/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/nix/store/cwxxbpfz2i2j34f3sgmd6vdl6wv98c2s-python3-3.6.4/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)                           
  File "/tmp/nix-build-python3.6-nnvm-0.8.drv-0/python/nnvm/__init__.py", line 6, in <module>
    from . import _base
  File "/tmp/nix-build-python3.6-nnvm-0.8.drv-0/python/nnvm/_base.py", line 47, in <module>
    _LIB = _load_lib()
  File "/tmp/nix-build-python3.6-nnvm-0.8.drv-0/python/nnvm/_base.py", line 39, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/nix/store/cwxxbpfz2i2j34f3sgmd6vdl6wv98c2s-python3-3.6.4/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)                     
OSError: /nix/store/8xzvqzqhdan9lviznks75ma8nczms55y-nnvm/lib/libnnvm_compiler.so: undefined symbol: _ZTIN3tvm4NodeE
```

I've done some investigation and found that `libnnvm_compiler.so` contains undefined symbol mentioned above, which is actually defined in `libtvm.so`

```
$ nm result/lib/libtvm.so | grep _ZTIN3tvm4NodeE                                                                                                                   
0000000000845dd0 V _ZTIN3tvm4NodeE
```

AFAIK, the Python module should be linked with both libraries, but putting path to libtvm.so in `LD_LIBRARY_PATH` didn't help. Could you please guess what I am missing here? How to ask Python to take `libtvm.so` into account?

Regards,
Sergey

**Comment by grwlf** [comment]
I've managed to solve the issue - I forgot to build tvm-python which brings the missing .so library.
